# vim:ft=ansible:
---
- hosts: aap
  vars:
    #for now data_folder has to be created on aap host and has to be owned by ec2-user
    data_folder: /mydata

  tasks:
    - name: Check if there is an existing ocp cluster installation
      ansible.builtin.find:
        paths: "{{ data_folder }}"
        file_type: any
        hidden: true
      register: files
    - name: Fail if the directory is not empty, a cluster is already created
      ansible.builtin.fail:
        msg: "The data directory {{ data_folder }} is not empty"
      when: files.matched != 0
    - name: Generate ocp install config from template
      ansible.builtin.template:
        src: ../templates/install-config.yml.j2
        dest: "{{ data_folder }}/install-config.yml"
